version: "2.1"
services:
  plexms:
    container_name: plex
    restart: always
    image: plexinc/pms-docker
    volumes:
      - "E:/media-server/config/plex:/config"
      - "C:/plex-transcode:/transcode"
      - "E:/media-server/data:/data"     
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=America/Denver
      - HOSTNAME="chillDesktopMedia"
      - PLEX_CLAIM="claim-xW1mVsbPFyGuFCQ_CsSm"
      - PLEX_UID=1000
      - PLEX_GID=1000
      - ADVERTISE_IP="http://96.19.177.169:32400/"
      - ALLOWED_NETWORKS=192.168.1.0/24