apiVersion: v1
kind: Service
metadata:
  name: lidarr
  labels:
    app: lidarr
    kubernetes.io/name: "lidarr"
spec:
  selector:
    app: lidarr
  ports:
  - name: lidarr
    port: 8686
    targetPort: 8686
  type: NodePort
